permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author:
  name: bolynn
  email: baolin1991@126.com
  link: http://www.baolinliu.com
  weibo: http://weibo.com/signup/signup.php?inviteCode=1833931013
  github: https://github.com/liubaolin
  music:
  linkedin:

# 站点信息
title: 浮天沧海
description: My personal blog
url: http://www.baolinliu.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/photo.jpg
favicon: /public/img/photo.jpg

# google analytics 设置
ga:
  id:
  url:


# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates:
  - Optimization
  - 读书

# 中文本地化
locals:
  tags: 分类
  about: 关于
  newest: 最新文章
  archive: 归档

gems: [jekyll-paginate]
